### PR TITLE
Cs169/remove extraneous gift recipient info clean

### PR DESCRIPTION
**Pull request by Ant1ng2**
Feature: Removed confidential information (i.e. Address, phone number) from being shown after submitting shipping information for a gift purchase.

- Added Flash error messages for already existing customers.
- Added another step definition to web_steps.rb
- Added more scenarios to gift.feature.

### CODE REVIEW

**Comment by Ant1ng2** [comment]
Here is the [link](https://travis-ci.org/raisindoc/audience1st/builds/522671186?utm_source=github_status&utm_medium=notification) to the passing TravisCI build for commit "Removed a whitespace".

**Comment by armandofox** [comment]
So I have an issue with the implementation of this feature. The problem with using `session` to store info like this is that the session gets polluted. In particular it doesn't appear that `session[:matching]` ever gets cleared out, and even if it did, you'd have to argue persuasively that that occurs on every path the customer could take through this flow.  It's already hard to keep track of the various things in the session, and in general it should only be used to store things whose lifetime really is comparable to the usage session.  Did you think about other ways to pass this info?  If the lifetime of this info is just a single action or single redirect, why not use hidden fields and/or `params` to pass it?

**Comment by Ant1ng2** [comment]
The method of using `params` sounds great! We'll go with that method in our next commit.

**Comment by Ant1ng2** [comment]
We have updated this PR with a lot of new changes
- We no longer use `session` to store the matching data.
- After the customer submits his credit card info, all 'confidential information' about the gifted is kept hidden.
- Added a few more tests.

Here's the [link](https://travis-ci.org/raisindoc/audience1st/builds/524793518?utm_source=github_status&utm_medium=notification) of a passing TravisCI.

**Pull request merged**
