### PR TITLE
Cs169/prevent guest checkout gift purchase clean

### PR DESCRIPTION
**Pull request by crazyberry7**
-created gift.feature that holds scenarios for gift checkout (remove confidential info and prevent gifting to oneself stories will use this file)
-all local rspec and Cuke tests pass

### CODE REVIEW

**Comment by armandofox** [comment]
The PR looks clean, which is great, but I'm concerned that still no Travis CI.  I'd feel a lot more confident if I knew that all the other scenarios/specs were still passing by seeing the CI badge.  Please advise.  I made an exception to my rule and merged the previous PR without a "CI checkoff" badge, but I don't want to keep making this exception since CI is there for a reason...

**Comment by crazyberry7** [comment]
Ignore the most recent PR for now; in regards to Travis CI checks, the build is failing because the wrong $KEY is used to decrypt. Isn't this key set in and passed through (as env. variables) your TravisCI repository settings since you're the owner of this github repo?

Looking at this link: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings 

This is a quote from that link: 

"we do not provide these values to untrusted builds, triggered by pull requests from another repository."

**Comment by armandofox** [comment]
it may be that you have to set it in travis yourself.  to be perfectly honest i'm not sure how 'untrusted builds' work but i will do a bit of research to clarify it.

nonetheless, though, my main issue is that the specs aren't even passing locally (ie this is not a travis-only problem) when you guys said they were.

i will see what i can learn about 'untrusted builds'

Armando Fox (pronouns: he, him)
Professor, Computer Science Division
Faculty Advisor, Digital Learning Strategy & MOOCLab
UC Berkeley Campus Equity Advisor
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox>

Learn to build software free at saas-class.org

**Comment by crazyberry7** [comment]
I responded to your comment about the specs not passing locally. Update to the most recent master and the specs should pass.

**Comment by armandofox** [comment]
unfortunately there is a conflicted file `gift.feature`.  it's possible this is because i didn't merge in the same order the PRs were made but i don't think so....

**Comment by crazyberry7** [comment]
Fixed merge conflicts

**Pull request merged**
