### PR TITLE
Fix oder item comments

### PR DESCRIPTION
**Pull request by chengchenghuang**
This PR fixes the bug appeared in the last email that the door list should always reflect the newest change of item-level comments instead of the original order-level comments. It has two scenarios that test the newest change of item-level comments for both regular tickets and tickets redeemed from open vouchers on doorlist.

### CODE REVIEW

**Comment by chengchenghuang** [comment]
https://rocky-ravine-27276.herokuapp.com/customers/1
This is the testing demo website. 
The specific door list bug can be seen fixed here:
https://rocky-ravine-27276.herokuapp.com/checkins/34/door_list

**Comment by armandofox** [comment]
i'm confused by the cucumber feature files.  it looks like each file contains multiple scenarios, but they are not separated out with different Scenario: headers.  please fix this.  also, can you please get CI to pass?

**Comment by armandofox** [comment]
thanks. i made a comment on the PR that will need to be addressed before i can merge.

Armando Fox (pronouns: he, him; él)
Professor, Computer Science Division
Faculty Advisor, Digital Learning Strategy & MOOCLab
UC Berkeley Campus Equity Advisor
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox>

Learn to build software free at saas-class.org

**Comment by armandofox** [comment]
You still need to DRY out the cucumber scenarios a lot.  There is a huge amount of repetition that needs to be pulled out into background steps.

Please work with teammates on this or consult your GSI if you're not sure what to do, as these concepts- code quality, DRYness, test coverage, etc - are the very basics of CS169, but for the PRs of this final iteration, those things seem to have gone out the window.  Code that's not clean, not DRY, and not test-covered is code that will never go into production - no exceptions.  Please let me know when I should be re-evaluating the current round of PRs.

**Comment by chengchenghuang** [comment]
@armandofox So we have updated the two feature files. We'd like to explain the difference between the two:
1. features/frontofhouse/tickets_comments_on_door_list.feature tests the correct display of comments after staff updates customer's comments, on door list. This only applies to regular tickets (i.e tickets customer purchased themselves).
2. features/frontofhouse/redeemed_tickets_comments_on_door_list.feature.feature tests the same feature, but with a different background : i.e redeemed tickets from subscription rather than regular tickets. Since the background are different, we split them into 2 feature files. Please let us know if there's anything else we can do to further DRY it out.

**Pull request merged**
