### PR TITLE
177107905 r/2 25 2021

### PR DESCRIPTION
**Pull request by JustinRWong**
PR for Iteration 1. Changes are for 4 strong params changes to prepare for Rails 4 migration
1. Labels
2. Seatmaps
3. Shows
4. Ticket Sales Imports

### CODE REVIEW

**Comment by JustinRWong** [comment]
Currently fixing Hound styling issues and travis ci failed build issue

**Comment by JustinRWong** [comment]
Travis CI PR Build fails by design due to security reasons when foreign fork makes a pull request. The issue is that the build is using environment variables from `abhinavDhulipala/audience1st` instead of `armandofox/audience1st`. Because our tenant names are different, the build fails.

Source: https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
"Travis CI makes encrypted variables and data available only to pull requests coming from the same repository (“internal pull requests”). These are considered trustworthy, as only members with write access to the repository can send them.

Pull requests sent from forked repositories do not have access to encrypted variables or data even if these are defined in the fork source project."


Possible work around: 
1. Branch directly off `armandofox/audience1st`, pull appropriate changes from `abhinavDhulipala/audience1st`, and create a PR so that environment variables are correct
2. Make [modification](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) to `armandofox/audience1st`.

**Comment by JustinRWong** [comment]
Requirements for the two individual work arounds:
1. Branching and pushing to golden repo will require granting write access to the repo. 
2. [Changing](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) the golden repo's `.travis.yml` file.

**Comment by JustinRWong** [comment]
> Requirements for the two individual work arounds:
> 
> 1. Branching and pushing to golden repo will require granting write access to the repo.
> 2. [Changing](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) the golden repo's `.travis.yml` file. See this [draft PR](https://github.com/armandofox/audience1st/pull/62), which only differs from this in the [`.travis.yml:21` file](https://github.com/abhinavDhulipala/audience1st/blob/177107905_r/2-25-2021-travis/.travis.yml#L21).

UPDATE: The [Draft build ](https://travis-ci.org/github/armandofox/audience1st/jobs/760563364)still failed because all environment variables were removed completely. Adding the travis script searches for `$TRAVIS_PULL_REQUEST` but it was stripped before the build even began.

**Comment by armandofox** [comment]
ugh, i hadn't thought about this.  i take it this is only an issue when you do a PR against the golden repo, and NOT an issue for your own internal use of travis, right?

Armando Fox (he, him, él)
Professor, Computer Science Division • Faculty Advisor, Digital Learning Strategy
UC Berkeley Campus Equity Advisor
390 Soda Hall MC#1776, Berkeley, CA, 94720-1776 • +1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox> • PGP/GPG key ID: 0x9AD0E747
-----
Washing your hands after being around others is a personal choice. 
Wearing a mask around others is a choice to be responsible and considerate.

**Comment by JustinRWong** [comment]
Correct. This is only an issue when creating a pr to the golden repo. Travis is fine on our own repo

**Pull request closed without merging**
