### PR TITLE
Advance sales report can be downloaded as .csv

### PR DESCRIPTION
**Pull request by Hexhu**
Now under /reports there should be two buttons for Advance Sales
  - Display on Screen (Renamed from the previous 'Go' button)
  - Download to Excel (new feature, generates and downloads a .csv of the desired report)

Preview: [https://tranquil-thicket-52105.herokuapp.com/reports](https://tranquil-thicket-52105.herokuapp.com/reports)

This feature follows this story: https://www.pivotaltracker.com/story/show/169792924

### CODE REVIEW

**Comment by Hexhu** [comment]
The heroku build is failing with the following log:

```
remote:        Running: rake assets:precompile
remote:        /tmp/build_64d3983c55d52c28fbff085b343aeb6b/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
remote:        The PGconn, PGresult, and PGError constants are deprecated, and will be
remote:        removed as of version 1.0.
remote:        
remote:        You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
remote:        
remote:        Called from /tmp/build_64d3983c55d52c28fbff085b343aeb6b/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_64d3983c55d52c28fbff085b343aeb6b/config/initializers/apartment.rb:10: Initializing workaround for Apartment gem issue 233
remote:        rake aborted!
remote:        Uglifier::Error: Unexpected token: operator (&). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
```

Not reproducible locally, but I still applied a fix as described in https://github.com/lautis/uglifier/issues/127

Now the error becomes
```
remote:        Running: rake assets:precompile
remote:        /tmp/build_b109480d4146ee69bee3399fc84c0559/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
remote:        The PGconn, PGresult, and PGError constants are deprecated, and will be
remote:        removed as of version 1.0.
remote:        
remote:        You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
remote:        
remote:        Called from /tmp/build_b109480d4146ee69bee3399fc84c0559/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_b109480d4146ee69bee3399fc84c0559/config/initializers/apartment.rb:10: Initializing workaround for Apartment gem issue 233
remote:        rake aborted!
remote:        Uglifier::Error: Unexpected token: operator (&)
```

**Comment by Hexhu** [comment]
Ah, fixed by disabling uglifier (by commenting out the line about `config.assets.js_compressor`)

**Comment by armandofox** [comment]
i don't want uglifier disabled.  please investigate the actual error.  there was a previous PR that included Ruby code (&:like_this) in a javascript file.  please make sure that stuff is gone and that isn't the cause of the error; i have never had problems with the asset pipeline before.

Armando Fox (pronouns: he, him; él)
Professor, Computer Science Division
Faculty Advisor, Digital Learning Strategy & MOOCLab
UC Berkeley Campus Equity Advisor
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox>

Learn to build software free at saas-class.org

**Comment by Hexhu** [comment]
Ah I see, it is in `app/assets/javascripts/seatmap.js` by @cyang2020 in #310f4cd, but it's actually not relevant to this feature. I will remove it from this PR.

**Comment by armandofox** [comment]
if you were doing a branch off of master, you should never have seen that commit, since i rejected the PR.

why is that code even part of your branch?

Armando Fox (pronouns: he, him; él)
Professor, Computer Science Division
Faculty Advisor, Digital Learning Strategy & MOOCLab
UC Berkeley Campus Equity Advisor
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox <http://www.cs.berkeley.edu/~fox>

Learn to build software free at saas-class.org

**Comment by Hexhu** [comment]
Understood, preparing a clean PR rn.

**Pull request closed without merging**
